import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree, Maitree, Lato, Kanit } from "next/font/google";
import "@/app/globals.css";
import { cn } from "@/lib/utils";
const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
});

const kanit = Kanit({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-kanit",
});

const lato = Lato({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-lato",
});

const maitree = Maitree({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-maitree",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" 
        className={cn(
        figtree.variable,
        maitree.variable,
        lato.variable,
        kanit.variable
      )}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#141616] text-[#228100]`}>
        {children}
      </body>
    </html>
  );
}
